### ISSUE TITLE
[make-indexes] NMOS Parameter Registers

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-doc-build-scripts#24]
Should we change the hard-coded list at https://github.com/AMWA-TV/nmos-doc-build-scripts/blob/d9396a3f4fe3fdcb9932e59e76c32a57412c4831/make-indexes.sh#L97 to just use the list of individual drectories (less the "common" and dot-dirs, ".github", ".render", ".lint")? At the moment even the capabilities branch doesn't list the capabilities register, and (update!) in fact doesn't seem to include the docs because and https://github.com/AMWA-TV/nmos-doc-build-scripts/blob/d9396a3f4fe3fdcb9932e59e76c32a57412c4831/extract-docs.sh#L84 also needs updating.

Bonus questions:
Should we move the common/*.md into the top-level, so that directories isn't a special case?
Should we move all of these under a "docs" directory?

**Comment by garethsb-sony** [comment]
The list of registers also appears in https://github.com/AMWA-TV/nmos-doc-layouts/blob/main/_layouts/default.html#L48-L58 :-/

**Comment by peterbrightwell** [comment]
I think now we have a lot more data-driven and templated parts of the render this can be closed. @garethsb  please reopen if you disagree :)
